import {
  ArrowDown,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  Blocks,
  BriefcaseBusiness,
  BookOpenCheck,
  ChartNoAxesCombined,
  Check,
  CircleCheck,
  CircleDashed,
  CodeXml,
  Compass,
  Copy,
  Crosshair,
  DraftingCompass,
  Database,
  FileBadge,
  FileCheck2,
  FileQuestion,
  FileText,
  FileLock2,
  Fingerprint,
  FlaskConical,
  Globe2,
  GraduationCap,
  Info,
  ListChecks,
  Linkedin,
  Github,
  LockKeyhole,
  Mail,
  Phone,
  MessageSquareText,
  Menu,
  MessageCircle,
  MoonStar,
  MoveRight,
  MoveUpRight,
  Network,
  Orbit,
  PanelsTopLeft,
  Plus,
  Quote,
  RefreshCw,
  Replace,
  RotateCcw,
  Scale,
  ScanSearch,
  Search,
  Server,
  Shield,
  ShieldAlert,
  ShieldCheck,
  SkipForward,
  Sparkles,
  Store,
  Sun,
  UserRound,
  UserRoundCheck,
  UsersRound,
  Wifi,
  Workflow,
  X
} from 'lucide-react';

const iconMap = {
  ArrowDown, ArrowDownRight, ArrowLeft, ArrowRight, ArrowUpRight, BadgeCheck, Blocks, BriefcaseBusiness,
  BookOpenCheck, ChartNoAxesCombined, Check, CircleCheck, CircleDashed, CodeXml, Compass, Copy,
  Crosshair, DraftingCompass, Database, FileBadge, FileCheck2, FileLock2, FileQuestion, FileText, Fingerprint, FlaskConical,
  Globe2, GraduationCap, Github, Info, Linkedin, ListChecks, LockKeyhole, Mail, MessageCircle, MessageSquareText, Menu, MoonStar, Phone,
  MoveRight, MoveUpRight, Network, Orbit, PanelsTopLeft, Plus, Quote, RefreshCw, Replace,
  RotateCcw, Scale, ScanSearch, Search, Server, Shield, ShieldAlert, ShieldCheck, SkipForward, Sparkles, Store, Sun,
  UserRound, UserRoundCheck, UsersRound, Wifi, Workflow, X
};

export function Icon({ name = 'Sparkles', size = 18, strokeWidth = 1.7, ...props }) {
  const Component = iconMap[name] || Sparkles;
  return <Component size={size} strokeWidth={strokeWidth} aria-hidden="true" {...props} />;
}
